deploy:
- provider: s3
  access_key_id: AKIAIX6VW5NAU5JCKXJA
  secret_access_key: &1
    secure: WlpqVtb00h/OmO4Wld/b0fVwelRnhbQMUQNil9tOB3su676DZO+IUHEb0dwAjRYGU3UAu3C3xElrcFrDraqGJu+NYkYQYhcp7NDcJdEQE1bTQbShSVGt/xL/Un0lR8q4YfN55PwkkdCWAx9myYO+8VdnYp9WD6kDoD7wGVoffO7PSzjAN3U2CLxG7ZQdYU5tpeALYHD092Fv+ouqJimcVm0gkP1wvgTuM2rIXC+lCenS/5s96XoGEPuTUEOJp6QfiOTuSk5ofJvOhRCfQnqqcO5uV6SQkBZUETj9K5kiLHkgoW6i1/uLeUDnP6mgQbOi/TidKwmWeBytj7ZwkNQhJCfEHYZ0WQS7lbPDK9AS4flWWrZfpCiHxeIMajCQBzkjlXvuJ+tplEbyJrW7hmUVmAAw5wCvnwjGOK29Cra+ovhkIdy/YC3cU4vUI3CIuGXsUii99tXp1BjAp3Jr7V+RJni2Hx8zZgeJ9BaETJZYzBzjgRR8MBOyzIB5X7K3dhFECHhgtr54XFsTfsj5SyZCVG+H/oSMP8huJQsGB4x8BZJofKR+1P9JUMiMkQZsWsRLQ1OLT0LVxudSXILAiv8+Ax2/e++sJ0LtkLVTZkwbNUx0aQL4oOxNaCEZMMZT48ul1uyjk8VGwnZmumc42HGuu7l3Hvjx/r2BNHewDUcTRYw=
  local_dir: dpl_cd_upload
  skip_cleanup: true
  on: &2
    repo: yejune/php-skeleton
  bucket: yejune-deploy
  upload_dir: latest
- provider: codedeploy
  access_key_id: AKIAIX6VW5NAU5JCKXJA
  secret_access_key: *1
  bucket: yejune-deploy
  key: latest/App.zip
  bundle_type: zip
  application: php-skeleton
  deployment_group: DeploymentGroup
  on:
    branch: release
before_deploy:
- mkdir -p dpl_cd_upload
- mv App.zip dpl_cd_upload/App.zip
after_deploy:
- /bin/bash ci/after_deploy.sh