project_name: development
stage_name: local
services:
  webserver:
    container_name: webserver
    image: yejune/webserver:7.1.4e
    expose:
      - '80'
    working_dir: /var/www
    environment:
      USE_SSL: on
      FPM_LISTEN: /dev/shm/php-fpm.sock
      FASTCGI_PASS: unix:/dev/shm/php-fpm.sock
stages:
  local:
    services:
      webserver:
        hostname: development.com
        volumes:
          - '.:/var/www'
          - './var/log/nginx:/var/log/nginx'
          - './var/certs:/var/certs'
        environment:
          TZ: Asia/Seoul
          DOMAIN: development.com
          STAGE_NAME: local
          DEBUG: 1
          MASTER_DATABASE_URL: mysql://root:root@mysql:3306/dev
          SLAVE1_DATABASE_URL: mysql://root:root@mysql:3306/dev
          REDIS_URL: redis
          NGINX_CORS: true
        links:
          - mysql
          - redis
      redis:
        container_name: redis
        image: redis:3.2.8-alpine
        expose:
          - '6379'
      mysql:
        container_name: mysql
        image: yejune/mysql
        expose:
          - '3306'
        environment:
          TZ: Asia/Seoul
          MYSQL_URL: 'mysql://user:pass@mysql:3306'
          MYSQL_ROOT_PASSWORD: root
          DOMAIN: mysql.development.com
          INITDB: |
            CREATE DATABASE IF NOT EXISTS `dev`;
        volumes:
          - './var/mysql:/var/lib/mysql'
  production:
    services:
      webserver:
        environment:
          DOMAIN: production.com
          STAGE_NAME: production
          DEBUG: 0
          MASTER_DATABASE_URL:
          SLAVE1_DATABASE_URL:
      links:
        - redis
tasks:
  composer:
    container: webserver
    cmd: composer
  phpunit:
    container: webserver
    cmd: phpunit
  phinx:
    container: webserver
    cmd: vendor/bin/phinx
  devtools:
    container: webserver
    cmd: vendor/bin/phalcon.php
  worker:
    container: webserver
    cmd: php public/cli.php
